package com.jainer.moviehub.model.util

// CLASSE ENUMERADA QUE DISPÕE OS TIPOS DE SUCESSO ESPERADOS PELO APLICATIVO
enum class AppSuccessType {
    LOGIN_SUCCESS,
    SIGNUP_SUCCESS,
    AUTH_CREDENTIAL_SUCCESS,
    FAKE_MOVIES_API_SUCCESS,
    MOVIE_LOCAL_DB_SUCCESS,
    FIREBASE_DB_SUCCESS,
    UNKNOWN_SUCCESS
}